name: Test CI

on: [push, pull_request]

jobs:
  test:
    name: test github actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm test

      - name: Run Build
        run: |
          npm run build
        env:
          CI: true
